### ISSUE TITLE
Don't emit an extra H1 title for index.html.json

### ISSUE THREAD

**Issue by sabine** [ocaml-doc/voodoo#133]
See https://docs-data.ocaml.org/live/p/cmdliner/1.2.0/doc/index.html.json.

There are two `h1` titles emitted here, one as part of the preamble, and one at the beginning of the content HTML body.

Only one title should be emitted.

Two titles are generated when the package has an `index.mld` file with a title.

---

See https://docs-data.ocaml.org/live/p/bst/7.0.1/doc/index.html.json

There is a title being emitted here as well that should be removed.

---

Resolves https://github.com/ocaml/ocaml.org/issues/1690.

**Comment by favonia** [comment]
Thank you for creating the issue for me. Just to be clear, I prefer removing the title _even if `index.mld` is not present,_ so that it is always consistent with the **Overview** page. :smiley_cat:

**Comment by sabine** [comment]
Yeah that seems fine, the title in https://ocaml.org/p/bst/latest/doc/index.html is not useful either.

**Comment by favonia** [comment]
@sabine That's arguable, because the library authors can use titles such as "Introduction" or a useful description of the package instead of the raw package name, but in any case it's always _more_ consistent without the extra title. 😉 If voodoo becomes something that everyone can (easily) use locally, I'm pretty confident that library authors will adapt.

**Comment by sabine** [comment]
Yeah that's what I try to say: when the index.mld page contains a title, that one will always be rendered because we're not stripping content. 🙂

**Comment by favonia** [comment]
@sabine Ah sorry I thought you were even complaining about the title in `index.mld`. I think we totally agree, then. 😅
